export const TRACKER_DEDUPLICATOR    = 'TRACKER_DEDUPLICATOR';
export const TRACKER_ROUTE_PREFIX    = 'TRACKER_ROUTE_PREFIX';
export const TRACKER_PLUGINS         = 'TRACKER_PLUGINS';
export const TRACKER_MODULE_OPTIONS  = 'TRACKER_MODULE_OPTIONS';
export const TRACKER_API_KEY         = 'TRACKER_API_KEY';
export const TRACKER_DISTINCT_CACHE_TTL_MS = 'TRACKER_DISTINCT_CACHE_TTL_MS';
export const TRACKER_ADMIN_KEY             = 'TRACKER_ADMIN_KEY';
