/**
 * The five event types supported by the tracker.
 *
 * Severity ordering (highest to lowest): `error > warning > info > debug > event`.
 * The `event` type represents custom analytics/tracking events and is always
 * captured regardless of the `TrackerClient`'s `minLevel` setting.
 *
 * @see {@link EVENT_SEVERITY} for the ordered array used in severity filtering.
 */
export type EventType = 'error' | 'warning' | 'info' | 'debug' | 'event';

/**
 * Severity ordering for level-based filtering.
 * Lower index = higher severity. Used by the client's `minLevel` option
 * to drop events below a configured threshold.
 *
 * @see {@link EventType}
 */
export const EVENT_SEVERITY: readonly EventType[] = ['error', 'warning', 'info', 'debug', 'event'] as const;

/**
 * Lifecycle status of a stored tracker event.
 *
 * Events start as {@link TrackerEventStatus.New | New} when ingested by the server
 * and can be updated through the status workflow via the
 * `PATCH /tracker/events/:id/status` endpoint.
 *
 * @see {@link StoredTrackerEvent.status}
 */
export enum TrackerEventStatus {
  /** Newly ingested, not yet reviewed. */
  New          = 'new',
  /** Viewed by a team member but no action taken. */
  Viewed       = 'viewed',
  /** Acknowledged — someone is aware and will handle it. */
  Acknowledged = 'acknowledged',
  /** Actively being investigated or fixed. */
  InProgress   = 'in_progress',
  /** Root cause addressed and deployed. */
  Resolved     = 'resolved',
  /** Intentionally ignored — not worth fixing. */
  WontFix      = 'wont_fix',
  /** Moved to archive — hidden from default views. */
  Archived     = 'archived',
}

/**
 * Contextual metadata attached to every {@link TrackerEvent}.
 *
 * Fields like `url` and `userAgent` are auto-populated by `TrackerClient`
 * when running in a browser. Server-side (Node.js) code should omit them
 * or set them explicitly via `TrackerClient.setContext()`.
 *
 * @see `TrackerClient.setContext()`
 * @see `TrackerClient.getContext()`
 */
export interface TrackerContext {
  /** Unique identifier for the current user (e.g. from your auth system). */
  userId?:      string;
  /** Session identifier — auto-generated by `SessionManager` or set manually. */
  sessionId?:   string;
  /** Application version string (e.g. `'36.0.0'`). */
  appVersion?:  string;
  /** Deployment environment. Used for filtering events in the dashboard and queries. */
  environment?: 'development' | 'staging' | 'production';
  /** Auto-set from `window.location.href` in browser; omit in Node. */
  url?:         string;
  /** Auto-set from `window.location.pathname` in browser; omit in Node. */
  path?:        string;
  /** Auto-set from `document.referrer` in browser; omit in Node. */
  referrer?:    string;
  /** Auto-set from `navigator.userAgent` in browser; omit in Node. */
  userAgent?:   string;
  /** Auto-set from `navigator.language` in browser; omit in Node. */
  language?:    string;
  /** Auto-set from `Intl.DateTimeFormat().resolvedOptions().timeZone` in browser; omit in Node. */
  timezone?:    string;
  /** Auto-set from `window.innerWidth/innerHeight` in browser; omit in Node. */
  viewport?:    { width: number; height: number };
  /** Auto-set from `screen.width/height` in browser; omit in Node. */
  screen?:      { width: number; height: number };
  /** Auto-set from `navigator.connection.effectiveType` in browser if available; omit otherwise. */
  connection?:  string;
}

/**
 * Serialized representation of an error across every tracker SDK
 * (TypeScript, Go, PHP). All fields beyond `name` / `message` are
 * optional so language differences (e.g. PHP's integer error codes,
 * Go's `runtime.Caller` frames) can populate the ones they have without
 * forcing the others to lie.
 *
 * @see `TrackerClient.error()` — populates this from a JS `Error`.
 * @see `tracker-php/SerializedError::fromThrowable` — PHP equivalent.
 * @see `tracker-go/SerializeError` — Go equivalent.
 */
export interface SerializedError {
  /** Error constructor name (e.g. `'TypeError'`, `'RangeError'`). */
  name:      string;
  /** Human-readable error description. */
  message:   string;
  /** Stack trace string, if available. */
  stack?:    string;
  /** Source file where the error originated (best-effort, parsed from the top stack frame). */
  file?:     string;
  /** Line number in `file`. Pairs with `file` when available. */
  line?:     number;
  /** Numeric or string error code (`AggregateError`, `Node SystemError.code`, custom error subclasses). */
  code?:     string | number;
  /** Chain of wrapped causes (`Error.cause` in JS, `getPrevious()` in PHP, `errors.Unwrap` in Go). Outermost-first. */
  previous?: SerializedErrorPrevious[];
}

/**
 * One link in the {@link SerializedError.previous} chain. Stack traces are
 * intentionally omitted — the root error's stack already covers the throw
 * site, and including every wrapper's stack would inflate the payload
 * without adding triage value.
 */
export interface SerializedErrorPrevious {
  name:    string;
  message: string;
  file?:   string;
  line?:   number;
  code?:   string | number;
}

/**
 * A tracker event as created by the client before server processing.
 *
 * This is the wire format sent from `TrackerClient` to the server.
 * After ingestion, the server stamps additional fields to produce a
 * {@link StoredTrackerEvent}.
 *
 * @see {@link StoredTrackerEvent} for the server-side representation with `id`, `status`, and `receivedAt`.
 * @see `TrackerClient.capture()` for the primary method that creates these events.
 */
export interface TrackerEvent {
  /** Event severity/category. */
  type:      EventType;
  /** Human-readable description of what happened. */
  message:   string;
  /** Optional app/service identifier — set at init, auto-stamped on every event. */
  appId?:    string;
  /** Arbitrary structured data associated with the event. */
  payload?:  Record<string, unknown>;
  /** Serialized error details, present when `type` is `'error'`. */
  error?:    SerializedError;
  /** Contextual metadata (user, session, environment, etc.). */
  context?:  TrackerContext;
  /** Free-form tags for categorization and filtering (e.g. `['auto-capture', 'uncaught-exception']`). */
  tags?:     string[];
  /** Logical grouping key (e.g. `'auction'`, `'payment'`). Auto-extracted by `TrackerClient.track()`. */
  category?: string;
  /** Unix ms, set by client at capture time. */
  timestamp: number;
  /**
   * Per-event deduplication opt-out. When `false`, the consumer's
   * deduplicator skips this event entirely (no fingerprint compute,
   * no cache read or write) — every occurrence reaches storage.
   *
   * Use for intentional repeated events from the same user/session
   * (lifecycle markers like `bid.place_committed`, analytics events,
   * retries that genuinely represent distinct occurrences). The SDK
   * stamps this automatically when `dedup.bypassMessages` /
   * `dedup.bypassPredicate` is configured at init time, but call
   * sites may also set it explicitly per event.
   *
   * Any value other than literal `false` (omitted, `true`, undefined)
   * means "let the dedup pipeline decide" — the wire field is purely
   * a client-side opt-out signal, not a request to dedup.
   */
  dedup?:    boolean;
}

/**
 * A tracker event after server-side processing and storage.
 *
 * Extends {@link TrackerEvent} with server-assigned fields: a unique `id`,
 * a workflow `status`, a `receivedAt` timestamp, and an optional `count`
 * for aggregated/collapsed duplicates.
 *
 * @see {@link TrackerEvent} for the client-side event shape.
 * @see {@link TrackerEventStatus} for the status lifecycle.
 */
export interface StoredTrackerEvent extends TrackerEvent {
  /** Server-assigned UUID (v4). */
  id:         string;
  /** Current lifecycle status of this event. */
  status:     TrackerEventStatus;
  /** Unix ms, set by server at ingestion time. */
  receivedAt: number;
  /** For aggregation: 1 = individual event, >1 = collapsed duplicates. */
  count?:     number;
}

/**
 * Function that transforms a {@link TrackerEvent} before it is queued or ingested.
 *
 * Enrichers run in order during the client capture pipeline. Both synchronous
 * and async enrichers are supported — if any enricher returns a `Promise`,
 * the remaining enrichers in the chain run asynchronously.
 *
 * @param event - The event to enrich.
 * @returns The enriched event, or a Promise resolving to the enriched event.
 *
 * @example
 * ```typescript
 * const addBuildInfo: EnricherFn = (event) => ({
 *   ...event,
 *   payload: { ...event.payload, buildSha: GIT_SHA },
 * });
 * ```
 *
 * @see `TrackerConfig.enrichers`
 */
export type EnricherFn = (event: TrackerEvent) => TrackerEvent | Promise<TrackerEvent>;

// ─── Breadcrumbs ────────────────────────────────────────────────────────────

/**
 * Category of a breadcrumb trail entry.
 *
 * @see {@link Breadcrumb}
 */
export type BreadcrumbCategory = 'navigation' | 'click' | 'console' | 'network' | 'custom';

/**
 * Severity level of a breadcrumb entry.
 *
 * @see {@link Breadcrumb}
 */
export type BreadcrumbLevel    = 'debug' | 'info' | 'warning' | 'error';

/**
 * A breadcrumb records a single action or event leading up to an error.
 *
 * Breadcrumbs are collected by the `BreadcrumbsPlugin` and attached to
 * error events, providing a timeline of what happened before the error occurred.
 *
 * @see {@link BreadcrumbCategory}
 * @see {@link BreadcrumbLevel}
 */
export interface Breadcrumb {
  /** Unix ms when the breadcrumb was recorded. */
  timestamp: number;
  /** What kind of action this breadcrumb represents. */
  category:  BreadcrumbCategory;
  /** Human-readable description of the breadcrumb. */
  message:   string;
  /** Severity level of this breadcrumb entry. */
  level?:    BreadcrumbLevel;
  /** Additional structured data associated with this breadcrumb. */
  data?:     Record<string, unknown>;
}
